export const GET_SPECTRUM_FROM_WEB_SOCKET = 'GET_SPECTRUM_FROM_WEB_SOCKET'
export const GET_SPECTRUM_FROM_REST_API = 'GET_SPECTRUM_FROM_REST_API'

export const STOP_WEBSOCKET = 'STOP_WEBSOCKET'
export const ACT_ON_SPECTRUM = 'ACT_ON_SPECTRUM'
export const RESET_FLAGS = 'RESET_FLAGS'

export const LOADING = 'LOADING'
export const ERROR = 'ERROR'


